feat: di v2
loilo-inc/logos pull request #3
Opened 2021-01-16 03:23 UTC by keroxp

See README.md

2021-01-18 00:36 UTC, hayama-junpei commented
@keroxp パッケージ間の依存関係が
di -> service -> di のように循環してimport cycleが発生するので
interfaceを別パッケージに抜き出す等をやらないといけなくなる気がします。
get時のtypesafe化をやるのではなく、constructor injectionやfield injectionでdi.Dの注入ではなく、使う型自体を注入する方向でtypesafe化を進めたほうがいいような気がしました。

あと、import cycleが問題にならずManifestの型を定義できるのであれば、di.Dを使わずにManifestをそのまま使っていいような気持ちになりました。

2021-01-18 01:00 UTC, keroxp commented
@hayama-junpei 
```go
type Alice {
  Bob *Bob `di:"Bob"`
}
type Bob {
  Alice *Alice `di:"Alice"`
}
```

こういう方向も考えはしたんですが、同じ型の別のフィールドがあった場合や、interfaceの場合の自動割り当てが出来ないので断念しています。その場合diタグにキーを記述することになると思うのですが、そうするとキーの管理が自動化できなくなるというデメリットがあります。

import cycleとifaceパッケージについてはある程度仕方ないのかなと思っています。どういう設計をしてもいつかは起き得るので。aws-sdkとかは全パッケージがそうなってます。

> di.Dを使わずにManifestをそのまま使って

これはどういう意味ですか？

2021-01-18 01:25 UTC, hayama-junpei commented
@keroxp 

> di.Dを使わずにManifestをそのまま使って

下記のようなイメージでした。

interfaceのパッケージ

```go
type Logger interface {
	Log(m string)
}

type Service interface {
	Serve()
}

type Manifest struct {
	Log Logger
	Srv Service
}

```

使う側のパッケージ

```go

type logger struct {
}

func (l *logger) Log(m string) {

}

type service struct {
	m *Manifest
}

func (s *service) Serve() {
	s.m.Log.Log("Serve")
}

func main() {
	m := new(Manifest)
	m.Log = new(logger)
	m.Srv = &service{m: m}
	m.Srv.Serve()
}
```

interfaceを別パッケージに分離したらimport cycle起きなくなるので、
di.Dを作らずともManifestのような構造体を作って引き回せばよくなってしまうと思いまして。
diの旨味がなくなる印象です。

2021-01-18 01:45 UTC, hayama-junpei commented
@keroxp  ↑説明が弱かったのでちょっと書き直しました

2021-01-18 02:00 UTC, hayama-junpei commented
> こういう方向も考えはしたんですが、同じ型の別のフィールドがあった場合や、interfaceの場合の自動割り当てが出来ないので断念しています。その場合diタグにキーを記述することになると思うのですが、そうするとキーの管理が自動化できなくなるというデメリットがあります。

大分難しい問題ですね

> interfaceの場合の自動割り当てが出来ない

これは本PRのようにSetメソッド側だけcode生成すればなんとかなりそうな予感はします(?)

> 同じ型の別のフィールドがあった場合や、

> diタグにキーを記述することになると思うのですが、そうするとキーの管理が自動化できなくなるというデメリット

型で解決するほうを主軸にして、キーで解決する方はオプションにするもしくは実装しなくてもいいような気もします。
専用の型を作ればいいわけですし。

2021-01-18 03:04 UTC, takkyuuplayer requested changes
README 通りに使えるかを中心に見て、タイポ等コメント

2021-01-18 03:04 UTC, takkyuuplayer commented on di/README.md
> +  num := s.D.Get("number").(int) // 1
s/number/num

2021-01-18 03:04 UTC, takkyuuplayer commented on di/README.md
> +  d := di.Domain(func(b *di.B) {
s/Domain/NewDomain/

2021-01-18 03:04 UTC, takkyuuplayer commented on di/README.md
> +  "github.com/loilo-inc/logos"
"github.com/loilo-inc/logos/di"

2021-01-18 03:04 UTC, takkyuuplayer commented on di/README.md
> +//go:generate github.com/loilo-inc/logos/cmd/digen $GOFILE
go run が抜けています

```
//go:generate go run github.com/loilo-inc/logos/cmd/digen
```

2021-01-29 12:24 UTC, keroxp commented
再考するためCloseします。
@hayama-junpei @takkyuuplayer レビューありがとうございました。

2021-01-29 12:24 UTC, closed without merging